name: Bump Version

on:
  push:
    branches: ["main"]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
        with:
          persist-credentials: false
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b  #v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Cargo.toml version to match github tag
        shell: bash
        env:
          RELEASE_TAG: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          VERSION=${RELEASE_TAG#v}
          sed -i 's/^version = ".*"/version = "'"$VERSION"'"/' Cargo.toml

      - name: Commit files and create tag
        env:
          RELEASE_TAG: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --tags
          git checkout -b release-$RELEASE_TAG
          git add .
          git commit -m "ci: update version string in docs"
          git tag -d $RELEASE_TAG
          git tag $RELEASE_TAG

      - name: Push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa  #master
        env:
          RELEASE_TAG: ${{ steps.tag_version.outputs.new_tag }}
        with:
          branch: release-${{ steps.tag_version.outputs.new_tag }}
          force: true
          tags: true